# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'druidshape' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for druidshape
  pod 'React', :path => '../node_modules/react-native', :subspecs => ['RCTImage']
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Google-Mobile-Ads-SDK'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
end
